# Generated by Django 5.0.4 on 2026-06-26 16:43

import apps.core.upload_to_filename
import apps.core.validators
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[apps.core.validators.PhoneNumberValidator()], verbose_name='Phone Number')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('logo', models.ImageField(upload_to=functools.partial(apps.core.upload_to_filename.maker, *('brand_logo/%Y/%m/',), **{'keys': ['name']}), verbose_name='Logo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_brand', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('category_picture', models.ImageField(blank=True, max_length=255, null=True, upload_to=functools.partial(apps.core.upload_to_filename.maker, *('media_picture/%Y/%m/',), **{'keys': ['name']}), validators=[apps.core.validators.PictureValidator()], verbose_name='Category Picture')),
                ('is_sub_category', models.BooleanField(default=False)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcategory', to='product.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('price', models.PositiveIntegerField(blank=True, null=True, validators=[apps.core.validators.PriceValidator()])),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large'), ('XXXL', 'Extra Extra Extra Large'), ('XXXXL', 'Extra Extra Extra Extra Large')], max_length=30, null=True, validators=[apps.core.validators.SizeValidator()], verbose_name='Size')),
                ('color', models.CharField(blank=True, choices=[('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('YELLOW', 'Yellow'), ('PURPLE', 'Purple'), ('ORANGE', 'Orange'), ('BLACK', 'Black'), ('WHITE', 'White'), ('GRAY', 'Gray'), ('BROWN', 'Brown'), ('PINK', 'Pink'), ('GOLD', 'Gold'), ('SILVER', 'Silver')], max_length=20, null=True, validators=[apps.core.validators.ColorValidator()], verbose_name='Color')),
                ('material', models.CharField(blank=True, choices=[('WOOD', 'Wood'), ('METAL', 'Metal'), ('PLASTIC', 'Plastic'), ('GLASS', 'Glass'), ('FIBER', 'Fiber'), ('LEATHER', 'Leather'), ('TEXTILE', 'Textile'), ('RUBBER', 'Rubber'), ('OTHER', 'Other')], max_length=100, null=True, validators=[apps.core.validators.MaterialValidator()], verbose_name='Material')),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('width', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('warranty', models.CharField(blank=True, choices=[('1', '1 Year'), ('2', '2 Years'), ('3', '3 Years'), ('4', '4 Years'), ('5', '5 Years')], max_length=20, null=True, validators=[apps.core.validators.WarrantyValidator()], verbose_name='Warranty')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_products', to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='product.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('product_picture', models.ImageField(blank=True, max_length=255, null=True, upload_to=functools.partial(apps.core.upload_to_filename.maker, *('media_picture/%Y/%m/',), **{'keys': ['product']}), validators=[apps.core.validators.PictureValidator()], verbose_name='Product Picture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_products', to='product.product')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ('-product',),
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('percentage_discount', models.IntegerField(blank=True, choices=[(5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%'), (55, '55%'), (60, '60%')], null=True, validators=[apps.core.validators.PercentageDiscountValidator()])),
                ('numerical_discount', models.IntegerField(blank=True, null=True, validators=[apps.core.validators.NumericalDiscountValidator()])),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('is_use', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1)),
                ('is_expired', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_code_discounts', to='product.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_code_discounts', to='product.product')),
            ],
            options={
                'verbose_name': 'Discount %',
                'verbose_name_plural': 'Discounts %',
                'ordering': ('update_time', '-create_time'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reply', models.BooleanField(default=False)),
                ('comment', models.TextField(max_length=500, verbose_name='Comment')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='product.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='product.product')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='AddToInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_add_to_inventory', to='product.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_add_to_inventory', to='product.product')),
            ],
            options={
                'verbose_name': 'AddToInventory',
                'verbose_name_plural': 'AddToInventories',
                'ordering': ('product',),
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_wishlist', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_wishlist', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorites Basket',
                'verbose_name_plural': 'Favorites Baskets',
                'ordering': ('user',),
            },
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name_user'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'category', 'brand'], name='indexes_product'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'brand'), name='unique_product'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['product', 'category'], name='product_dis_product_b6c6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'product'], name='indexes_comment'),
        ),
        migrations.AddIndex(
            model_name='addtoinventory',
            index=models.Index(fields=['inventory', 'product'], name='product_add_invento_b6079c_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'product'], name='product_wis_user_id_e8ce35_idx'),
        ),
    ]
