services:
  db:
    image: postgres:alpine
    restart: on-failure
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: on-failure

  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: on-failure

  celery-worker:
    image: celery:alpine
    restart: on-failure
    command: celery worker -A config -l info
    volumes:
      - ./apps:/code/apps
      - ./config:/code/config
      - ./utility:/code/utility
    depends_on:
      - db
      - redis
      - rabbitmq

  celery-beat:
    image: celery:alpine
    restart: on-failure
    command: celery beat -A config -l info
    volumes:
      - ./apps:/code/apps
      - ./config:/code/config
      - ./utility:/code/utility
    depends_on:
      - db
      - redis
      - rabbitmq

networks:
  default:

volumes:
  postgres_data:
