# Generated by Django 5.0.4 on 2026-06-26 16:43

import apps.core.mixin.mixin_model
import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('total_price', models.IntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[apps.core.validators.QuantityValidators()], verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(default=0, validators=[apps.core.validators.AmountValidator()], verbose_name='Amount')),
                ('cardholder_name', models.CharField(max_length=100, validators=[apps.core.validators.NameValidator()], verbose_name='Cardholder Name')),
                ('card_number', models.CharField(max_length=12, validators=[apps.core.validators.CardNumberValidator()], verbose_name='Card Number')),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=4, validators=[apps.core.validators.CVVValidator()], verbose_name='CVV')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('transaction_payment', models.CharField(default=apps.core.mixin.mixin_model.generate_transaction_id, max_length=36, unique=True, verbose_name='Transaction Payment')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='Payment Time')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_failed', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Order Payment',
                'verbose_name_plural': 'Order Payments',
                'ordering': ['-payment_time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20, validators=[apps.core.validators.StatusValidator()], verbose_name='Status')),
                ('transaction_id', models.CharField(default=apps.core.mixin.mixin_model.generate_transaction_id, max_length=36, unique=True, verbose_name='Transaction')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=20)),
                ('code_discount', models.CharField(blank=True, max_length=100, null=True, validators=[apps.core.validators.CodeValidator()], verbose_name='Code Discount')),
                ('finally_price', models.IntegerField(default=0, validators=[apps.core.validators.FinallyPriceValidator()])),
                ('time_accepted_order', models.DateTimeField(blank=True, null=True, verbose_name='Time Accepted Order')),
                ('accepted_order', models.BooleanField(default=False)),
                ('time_shipped_order', models.DateTimeField(blank=True, null=True, verbose_name='Time Shipped Order')),
                ('shipped_order', models.BooleanField(default=False)),
                ('time_deliver_order', models.DateTimeField(blank=True, null=True, verbose_name='Time Deliver Order')),
                ('deliver_order', models.BooleanField(default=False)),
                ('time_rejected_order', models.DateTimeField(blank=True, null=True, verbose_name='Time Rejected Order')),
                ('rejected_order', models.BooleanField(default=False)),
                ('time_cancelled_order', models.DateTimeField(blank=True, null=True, verbose_name='Time Cancelled Order')),
                ('cancelled_order', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_order', to='account.address')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-create_time'],
            },
        ),
    ]
