# Generated by Django 5.0.4 on 2026-06-26 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_items', to='product.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(related_name='order_items', to='order.orderitem', verbose_name='Order Items'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='order.order'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['user', 'product'], name='order_item'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['address'], name='user_order_items'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['payment_time', 'order'], name='order_order_payment_3c08a7_idx'),
        ),
    ]
