# Generated by Django 5.0.4 on 2026-06-26 16:43

import apps.core.upload_to_filename
import apps.core.validators
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, validators=[apps.core.validators.NameValidator()], verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, validators=[apps.core.validators.LastNameValidator()], verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10, validators=[apps.core.validators.GenderValidator()], verbose_name='Gender')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Age')),
                ('profile_picture', models.ImageField(blank=True, max_length=255, null=True, upload_to=functools.partial(apps.core.upload_to_filename.maker, *('profile_picture/%Y/%m/',), **{'keys': ['name']}), validators=[apps.core.validators.PictureValidator()], verbose_name='Profile Picture')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'ordering': ('-update_time', '-create_time'),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ('-update_time', '-create_time'),
            },
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(verbose_name='user id')),
                ('token_type', models.PositiveSmallIntegerField(choices=[(1, 'access token'), (2, 'refresh token')], verbose_name='token type')),
                ('device_login_count', models.PositiveSmallIntegerField(default=0, verbose_name='device login count')),
                ('uuid', models.UUIDField(unique=True, verbose_name='uuid')),
            ],
            options={
                'verbose_name': 'UserAuth',
                'verbose_name_plural': 'UserAuths',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=100, unique=True, validators=[apps.core.validators.UsernameValidator()], verbose_name='Username')),
                ('email', models.EmailField(max_length=100, unique=True, validators=[apps.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[apps.core.validators.PhoneNumberMobileValidator()], verbose_name='Phone Number')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('-update_time', '-create_time', 'is_deleted'),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('address_name', models.CharField(max_length=50, validators=[apps.core.validators.NameValidator()], verbose_name='Address Name')),
                ('country', models.CharField(choices=[('Iran', 'Iran')], max_length=100, validators=[apps.core.validators.CountryValidator()], verbose_name='Country')),
                ('city', models.CharField(choices=[('Tehran', 'Tehran'), ('Shiraz', 'Shiraz'), ('Mashhad', 'Mashhad'), ('Tabriz', 'Tabriz'), ('Isfahan', 'Isfahan'), ('Kish', 'Kish'), ('Kerman', 'Kerman'), ('Zahedan', 'Zahedan'), ('Fars', 'Fars'), ('Semnan', 'Semnan'), ('Yazd', 'Yazd'), ('Qom', 'Qom'), ('Ahvaz', 'Ahvaz'), ('Gilan', 'Gilan'), ('Khorasan', 'Khorasan'), ('Kermanshah', 'Kermanshah'), ('Kohgiluyeh and BoyerAhmad', 'Kohgiluyeh and BoyerAhmad'), ('Lorestan', 'Lorestan'), ('Mazandaran', 'Mazandaran'), ('Markazi', 'Markazi'), ('Hormozgan', 'Hormozgan'), ('Hamadan', 'Hamadan'), ('Ardabil', 'Ardabil'), ('Zanjan', 'Zanjan'), ('Qazvin', 'Qazvin'), ('Kurdistan', 'Kurdistan')], max_length=100, validators=[apps.core.validators.CityValidator()], verbose_name='City')),
                ('street', models.CharField(max_length=200, validators=[apps.core.validators.StreetValidator()], verbose_name='Street')),
                ('building_number', models.CharField(max_length=20, validators=[apps.core.validators.BuildingNumberValidator()], verbose_name='Building Number')),
                ('floor_number', models.IntegerField(default=0, verbose_name='Floor Number')),
                ('postal_code', models.PositiveSmallIntegerField(default=0, verbose_name='Postal Code')),
                ('notes', models.TextField(blank=True, null=True, validators=[apps.core.validators.NotesValidator()], verbose_name='Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='user_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ('-update_time', '-create_time'),
            },
        ),
        migrations.CreateModel(
            name='CodeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('role_name', models.CharField(choices=[('golden', 'Golden'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=100, verbose_name='Role Name')),
                ('code', models.CharField(max_length=100, validators=[apps.core.validators.CodeValidator()], verbose_name='Code')),
                ('percentage_discount', models.SmallIntegerField(blank=True, choices=[(5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%'), (55, '55%'), (60, '60%')], null=True, validators=[apps.core.validators.PercentageDiscountValidator()], verbose_name='Percentage Discount')),
                ('numerical_discount', models.SmallIntegerField(blank=True, null=True, validators=[apps.core.validators.NumericalDiscountValidator()], verbose_name='Numerical Discount')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('is_use', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1)),
                ('is_expired', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'discount code',
                'verbose_name_plural': 'discount codes',
                'ordering': ('-update_time', '-create_time'),
                'indexes': [models.Index(fields=['code'], name='index_code')],
            },
        ),
        migrations.AddConstraint(
            model_name='codediscount',
            constraint=models.UniqueConstraint(fields=('code', 'role_name'), name='unique_code_discount_role_name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='bronze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze_roles', to=settings.AUTH_USER_MODEL, verbose_name='Bronze'),
        ),
        migrations.AddField(
            model_name='role',
            name='code_discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.codediscount', verbose_name='Discount Code'),
        ),
        migrations.AddField(
            model_name='role',
            name='golden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='golden_roles', to=settings.AUTH_USER_MODEL, verbose_name='Golden'),
        ),
        migrations.AddField(
            model_name='role',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='role',
            name='silver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silver_roles', to=settings.AUTH_USER_MODEL, verbose_name='Silver'),
        ),
        migrations.AddIndex(
            model_name='userauth',
            index=models.Index(fields=['user_id'], name='user_id_index'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'email', 'phone_number'], name='index_username_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_username_email'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'address_name'], name='index_user_postal_code'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('user', 'address_name'), name='unique_user_address_name'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='index_user_profile'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['golden', 'silver', 'bronze'], name='golden_silver_bronze_index'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('golden',), name='unique_golden'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('silver',), name='unique_silver'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('bronze',), name='unique_bronze'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('seller',), name='unique_seller'),
        ),
    ]
